---
title: "Quarto Dashboard"
format: 
  dashboard:
    theme: darkly
server: shiny
---

```{r echo = FALSE, eval = FALSE}
# This quarto document uses a Dashboard format, and runs a local shiny app.
# More information about Dashboards with Shiny:
# https://quarto.org/docs/dashboards/interactivity/shiny-r.html
```


```{r}
#| context: setup
#| include: false
library(shiny)
library(tidyverse)
```


# {.sidebar}

```{r}
selectInput(
  inputId = "variable",
  label = "Select variable:",
  choices = c("eruptions", "waiting"),
  selected = "eruptions")

sliderInput(
  inputId = "bins",
  label = "Number of bins",
  min = 1, 
  max = 30,
  value = 15)

checkboxInput(
  inputId = "show_mean",
  label = "Show mean",
  value = FALSE)
```


# Histogram

```{r}
plotOutput(outputId = "histogram")
```


# Table

```{r}
dataTableOutput(outputId = "table")
```



```{r}
#| context: server

output$histogram <- renderPlot({
  gg = ggplot(data = faithful, 
              mapping = aes(x = .data[[input$variable]])) +
    geom_histogram(bins = input$bins, color = "white") +
    labs(title = paste("Histogram of", input$variable, "time"))
  
  if (input$show_mean) {
    mean_time = mean(faithful[[input$variable]])
    gg + geom_vline(xintercept = mean_time, 
                    color = "red", 
                    alpha = 0.7,
                    linewidth = 2)
  } else {
    gg
  }
})


output$table <- renderDataTable({
  faithful
})
```

